### ISSUE TITLE
enhancements

### ISSUE THREAD

**Issue by Bizarrus** [aaronjwood/cracker#1]
- Input for **own** character set (for sample, i want only mixed alpha-numeric with **.-_** characters)
- Current status on cracking loop

**Comment by aaronjwood** [comment]
I added some progress reporting https://github.com/aaronjwood/cracker/commit/0c2c3fe8ad71b2bb492b25aa986a67a42a5ad4a2

**Comment by aaronjwood** [comment]
Opened a new issue for the custom character set support https://github.com/aaronjwood/cracker/issues/3
